global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CrewAI 應用程式監控
  - job_name: 'crewai-app'
    static_configs:
      - targets: ['crewai-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ChromaDB 監控
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 30s

  # PostgreSQL 監控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis 監控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter (系統監控)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 